### ISSUE TITLE
django.db.utils.ProgrammingError when enabling 2 factor auth according to documentation

### ISSUE THREAD

**Issue by aesraethr** [hoover/docker-setup#70]
`/opt/hoover# docker-compose run --rm search ./manage.py invite Tybalt
Starting hoover_search-es_1          ... done
Starting hoover_snoop-tika_1         ... done
Starting hoover_snoop-rabbitmq_1     ... done
Starting hoover_search-pg_1          ... done
Starting hoover_ui_1                 ... done
Starting hoover_snoop--testdata_1    ... done
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "twofactor_invitation" does not exist
LINE 1: DELETE FROM "twofactor_invitation" WHERE "twofactor_invitati...
                    ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/opt/hoover/search/hoover/contrib/twofactor/management/commands/invite.py", line 17, in handle
    url = invitations.invite(username, duration, create)
  File "/usr/local/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/opt/hoover/search/hoover/contrib/twofactor/invitations.py", line 20, in invite
    models.Invitation.objects.filter(user=user).delete()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 609, in delete
    deleted, _rows_count = collector.delete()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/deletion.py", line 288, in delete
    count = qs._raw_delete(using=self.using)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 623, in _raw_delete
    return sql.DeleteQuery(self.model).delete_qs(self, using)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/subqueries.py", line 81, in delete_qs
    cursor = self.get_compiler(using).execute_sql(CURSOR)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.7/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "twofactor_invitation" does not exist
LINE 1: DELETE FROM "twofactor_invitation" WHERE "twofactor_invitati...`

**Comment by mgax** [comment]
It looks like the migrations for twofactor were not run. Can you please repeat the step `docker-compose run --rm search ./manage.py migrate` after enabling 2fa?

**Comment by aesraethr** [comment]
indeed it fixed the issue. It should be added to the documentation.
